- LearnsMate/build.gradle
- LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/dto/AdminDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/entity/Admin.java
- LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminServiceImpl.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/controller/CampaignTemplateController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/CampaignTemplate.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/dto/CampaignTemplateDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/vo/request/RequestRegisterTemplateVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/vo/response/ResponseRegisterTemplateVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/repository/CampaignTemplateRepository.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignTemplateService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignTemplateServiceImpl.java
- LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SwaggerConfig.java
- LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
<br/>
- Admin 예외처리를 위해 추가
- Admin <-> AdminDTO 간 convert 메소드 추가
- swagger 추가
- 캠페인 템플릿 등록 코드 추가 (컨트롤러, 서비스)
<br/>
코드 작성 + 잘 실행되는지도 확인했습니다.
<br/>
- 캠페인 템플릿 수정, 삭제, 조회 관련 기능 추가
<br/>
close #2
> Feature/campaign template (#2) : 캠페인 템플릿 등록 코드 추가 및 Admin 관련 메소드 추가 + swagger 적용

- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/entity/Campaign.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/entity/CampaignTypeEnum.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
- 제목 : feat(#3 ): 캠페인 등록 기능을 위한 registCampaign 메서드 추가
<br/>
- 즉시발송/예약발송에 따라 sendDate가 바뀌도록 캠페인 등록 기능을 만들었습니다.
<br/>
<br/>
- 캠페인 수정 기능
<br/>
close #3
> ✨ 기능 추가: 캠페인 등록 기능을 위한 registCampaign 메서드 추가

- LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/controller/CampaignTemplateController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignTemplateService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignTemplateServiceImpl.java
<br/>
우선 DTO에 삭제 원하는 템플릿 코드를 넣고 나머지는 NULL인 상태로 서비스 코드에서 넣어줬던 템플릿 코드로 찾아온 뒤, Flag 를 False로 나타내 삭제 처리를 해주었습니다.
<br/>
<br/>
- 조회 API 추가
<br/>
close #36
> feat(#36 ): 캠페인 삭제 API 추가

- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestRegisterCampaignVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseEditCampaignVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseRegisterCampaignVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
- 제목 : feat(#45 ): 캠페인 취소 기능 추가
<br/>
- 예약된 캠페인은 취소 될 수 있습니다.
<br/>
<br/>
- 캠페인 전체 조회
<br/>
close(#45 )
> ✨ 기능 추가: CampaignService -> 캠페인 취소 기능 추가

- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/entity/Campaign.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseFindCampaignVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
- 제목 : feat(#50 ): 캠페인 전체 조회 기능 추가
<br/>
- 보내진/보내질 전체 캠페인을 조회할 수 있습니다.
<br/>
<br/>
- 캠페인 코드로 캠페인 단건 조회 기능
<br/>
> ✨ 기능 추가: CampaignService -> 캠페인 전체 조회 기능 추가

- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestFindCampaignByCampaignCodeVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
- 제목 : feat(#53  ): 캠페인 단건 조회 기능 추가
<br/>
- 캠페인 코드로 캠페인 단건 조회가 가능합니다.
<br/>
<br/>
- 제목으로 조회, 기간별 조회, 발송타입별 조회, 발송된 캠페인 조회, 발송될 캠페인 조회
<br/>
> ✨ 기능 추가: CampaignService -> 캠페인 단건 조회 기능 추가

- LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VocController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/Voc.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/dto/VocDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/response/ResponseFindVocVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/mapper/VocMapper.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VocRepository.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VocService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VocServiceImpl.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/domain/VocCategory.java
- 제목 : feat(#56, #57 ): VOC 전체 조회, 단 건 조회 기능 추가
<br/>
VOC 컨트롤러, 서비스, 리포지토리, Mapper, DTO, VO로 전체 조회, 단 건 조회 로직을 구현했습니다.
<br/>
<br/>
- VOC 답변의 CRUD를 담당해서 만들 예정입니다.
<br/>
close #56, #57
> feat(#56, #57 ): VOC 전체 조회, 단 건 조회 기능 추가

- LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/IssueCoupon.java
- LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/dto/IssueCouponDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/vo/request/IssueCouponRegisterRequestVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/vo/response/IssueCouponRegisterResponseVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/mapper/IssueCouponMapper.java
- LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/IssueCouponRepository.java
- LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
<br/>
발급 쿠폰 등록 기능 추가되었고 캠페인에서 N명의 학생에게 M개의 쿠폰을 각각 넣어줘야 하기 때문에 해당 발급 쿠폰 코드를 등록할 때 VO는 List로 넣어져서 요청이 될 것이라 그렇게 만들었습니다. List의 크기만큼 반복하면서 일일이 넣어줄 수 있는 코드를 구현했고 메소드로 구분해놨습니다.
<br/>
close #86
> feat(#86 ): 발급 쿠폰 등록 기능 추가

- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignCouponVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignStudentVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
- LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
- LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/mapper/CouponByCampaignMapper.java
- LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/repository/CouponByCampaignRepository.java
- LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/service/CouponByCampaignService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/service/CouponByCampaignServiceImpl.java
- LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java
- LearnsMate/src/main/java/intbyte4/learnsmate/userpercampaign/repository/UserPerCampaignRepository.java
- LearnsMate/src/main/java/intbyte4/learnsmate/userpercampaign/service/UserPerCampaignService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/userpercampaign/service/UserPerCampaignServiceImpl.java
- 제목 : feat(#99 ):  editCampaign 수정
<br/>
- 기존 캠페인 제목, 내용, 발송 시간만 수정 가능하던 기능에서 학생, 쿠폰도 수정 가능하게 변경했습니다.
<br/>
<br/>
- 제목으로 조회
<br/>
> ✨ 기능 수정: CampaignService -> editCampaign 수정

- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/dto/BlacklistReportCommentDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseFindReservedBlacklistOneVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/mapper/BlacklistMapper.java
- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/report/repository/ReportRepository.java
- LearnsMate/src/main/java/intbyte4/learnsmate/report/service/ReportService.java
- 제목 : feat(#100 ): 기능명 ✨ 기능 추가 / 수정: 학생, 강사 예비 블랙리스트 단건 조회 메서드 추가
<br/>
학생, 강사 예비 블랙리스트를 조회하는 메서드를 구현했습니다.
신고내역이 5회 이상인 멤버가 예비 블랙리스트로 처리되는데 
이때, 단건 조회시 신고내역과 어떤 댓글로 신고를 당했는지 확인하기 위해서 report, comment service를 사용했습니다.
<br/>
예비 블랙리스트를 따로 테이블로 빼도 괜찮을거 같다는 생각을 했습니다.
<br/>
close #100
> ✨ 기능 추가 / 수정: 학생, 강사 예비 블랙리스트 단건 조회 메서드 추가

- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseFindCampaignByTypeVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepository.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
- 제목 : feat(#114 ): findCampaignsByType 추가
<br/>
- 캠페인 타입이 INSTANT이면 즉시발송만 조회, RESERVATION이면 예약발송만 조회 가능
<br/>
<br/>
- 제목으로 조회, 기간별 조회
<br/>
> ✨ 기능 추가: CampaignService -> findCampaignsByType 추가

- LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureFilterDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/request/RequestLectureFilterVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepository.java
- LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepositoryImpl.java
<br/>
- 필터 적용한 강의 조회 기능
<br/>
<br/>
- gpt 프롬프팅
<br/>
close #180
> feat(#180): 필터 적용한 강의 조회 기능

- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/dto/BlacklistDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/dto/BlacklistFilterRequestDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/request/RequestFilterBlacklistMemberVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseFindBlacklistVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/mapper/BlacklistMapper.java
- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepository.java
- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepositoryCustom.java
- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepositoryImpl.java
- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryImpl.java
- 제목 : feat(#183 ): 기능명 [✨ 기능 추가 / 수정: 멤버 타입에 따른 블랙리스트 필터링 메서드 추가]
<br/>
블랙리스트 디티오 변경
멤버 타입에 따른 블랙리스트 필터링 추가
<br/>
<br/>
프론트 제작
<br/>
close #183
> ✨ 기능 추가 / 수정: 멤버 타입에 따른 블랙리스트 필터링 메서드 추가

- LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java
- LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
- LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
- LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/RequestRegisterPaymentVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/payment/mapper/PaymentMapper.java
- LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
<br/>
결제 정보 등록 기능 추가됐던 것 장바구니 개념이 없어서 List로 받던 것을 일부 수정했습니다.
추가로 쿠폰 사용 시 사용했다는 데이터 수정 또한 추가했습니다.
<br/>
close #151 
close #160
> feat(#151 #160 ): 결제 정보 등록 기능 수정

- LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/reqeust/RequestCountByCategoryVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
- 제목 : feat(#194 ): VOCService -> countVOCByCategory 수정
<br/>
- 기존 VOC 카테고리 별 VOC 개수 조회에서 지정된 기간 내 개수 조회가 가능하도록 수정했습니다.
<br/>
<br/>
- 프론트엔드
<br/>
> ✨ 기능 수정: VOCService -> countVOCByCategory 수정

- LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/entity/Member.java
- LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/controller/PreferredTopicsController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/domain/dto/PreferredTopicStatsConvertDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/domain/dto/PreferredTopicStatsDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/domain/dto/PreferredTopicsDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/domain/vo/response/ResponseFindMonthlyStatsVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/mapper/PreferredTopicsMapper.java
- LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/repository/PreferredTopicsRepository.java
- LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/service/PreferredTopicsService.java
- 제목 : feat(#196 ): 기능명 ✨ 기능 추가 / 수정: 카테고리 별 학생 비율 그래프 메서드 작성
<br/>
카테고리 별 학생 비율 그래프를 위해서 mvc 메서드를 만들었습니다.
복잡하지 않았는데 JPQL을 작성하는데에서 자꾸 오류가 발생했습니다.
1. 이미지에서 현재는 YEAR, MONTH를 따로 사용하고 있는데 기존 방법의 yearMonth를 가져오기 위해서
FUNCTION('DATE_TIME', ~)메서드를 사용했을때 계속해서 에러가 발생했습니다.
현재까지는 저희가 추가한 hibernate에서 지원하지 않는 포맷이라서 안되는걸로 생각하고 있는데 아직 확실치 않습니다. 이건 추가로 공부해봐야 할거같습니다. 
2. 그리고 lectureCategoryName가 String으로 저장되어있다고 생각해서 String을 고집했었으나 entity에는 enum으로 저장되어 있어서 enum으로 받아왔고 바꾸니 에러가 사라졌습니다.
year, month를 따로 가져왔기 때문에 서비스 코드에서 둘을 '-' 기호를 통해 합쳐주는 부분을 추가했습니다.
<br/>
<br/>
다음 통계 데이터 작성 및 DATE_FORMAT 에러 발생 이유 찾기
<br/>
> ✨ 기능 추가 / 수정: 카테고리 별 학생 비율 그래프 메서드 작성

- LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/dto/VOCFilterRequestDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/dto/VOCPageResponse.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/request/RequestFilterVOCVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/mapper/VOCMapper.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepositoryCustom.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepositoryImpl.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCFacade.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
<br/>
voc 전체 조회 시, 필터링 시 페이지네이션 관련 추가했습니다.
<br/>
> voc 전체 조회 시, 필터링 시 페이지네이션 관련 추가

- LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java
- LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
<br/>
✨기능 추가: 블랙리스트 admin 찾아오는 코드 추가, 회원 상세조회시 추천강의 안보여 로그 추가
<br/>
> ✨기능 추가: 블랙리스트 admin 찾아오는 코드 추가

- LearnsMate/build.gradle
- LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java
- LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/dto/ResponseEmailDTO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/entity/Admin.java
- LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/request/AdminEmailVerificationVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/request/EmailVerificationVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/request/RequestResetPasswordVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/response/ResponseEmailMessageVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminServiceImpl.java
- LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/EmailService.java
- LearnsMate/src/main/java/intbyte4/learnsmate/common/config/EmailConfig.java
- LearnsMate/src/main/java/intbyte4/learnsmate/common/config/RedisConfig.java
- LearnsMate/src/main/java/intbyte4/learnsmate/security/AuthenticationFilter.java
- 제목 : feat:✨ 기능 추가 : AdminEmailVerificationVO 이메일에 따른 사번 검증 VO 기능 추가
<br/>
[POST} /admin/verification-email/password -> 인증버튼(비밀번호 재설정시 이메일 전송 API)
[POST} /admin/verification-email/confirmation -> 다음 버튼(비번 재설정 전 이메일 인증번호 검증)
[POST} /admin/password -> // 다음버튼 누를 시, 인증성공하면 ? -> 비번 재설정 칸 생성 -> 완료 버튼(비밀번호 재설정)
<br/>
<br/>
- 리프레시 토큰도 발행 후,  레디스에 담기
<br/>
> ✨ 기능 추가 : AdminEmailVerificationVO 이메일에 따른 사번 검증 VO 기능 추가

- LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/AdminCouponEditRequestVO.java
- LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java
- LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
<br/>
- 쿠폰 수정 시 날짜 db에 저장되도록 수정
- 쿠폰 전체 조회 시 adminCode도 반환되도록 수정
<br/>
<br/>
- 프론트 css 수정
<br/>
> ♻️ 코드 수정 : 쿠폰 수정 시 날짜 db에 저장되도록 수정

- .github/workflows/deploy.yml
- LearnsMate/src/main/java/intbyte4/learnsmate/common/config/AppConfig.java
- LearnsMate/src/main/java/intbyte4/learnsmate/common/config/BatchConfig.java
- LearnsMate/src/main/java/intbyte4/learnsmate/common/config/RedisConfig.java
- LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
trationDelegate$BeanPostProcessorChecker : Bean 'jobRegistry' of type [org.springframework.batch.core.configuration.support.MapJobRegistry] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting eagerly injected/applied to a currently created BeanPostProcessor [jobRegistryBeanPostProcessor]? Check the corresponding BeanPostProcessor declaration and its dependencies/advisors. If this bean does not have to be post-processed, declare it with ROLE_INFRASTRUCTURE.
위와 같은 오류가 뜨는 것 같아 수정해봤습니다.
> ✨ 기능 수정 : RedisConfig 수정
