LearnsMate/LearnsMateBackend

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/entity/Campaign.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
- 제목 : Campaign 기본 세팅 추가
<br/>
- Campaign 도메인 기초 세팅
<br/>
<br/>
- 캠페인 등록 기능
<br/>
=> ✨ 기능 추가: Campaign 기본 세팅 추가

LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/controller/CampaignTemplateController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/CampaignTemplate.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/repository/CampaignTemplateRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignServiceImpl.java
<br/>
캠페인 템플릿 기능 개발 전 기본 세팅을 추가했습니다.
<br/>
기본 세팅을 활용해서 오류가 없게끔 해 비즈니스 로직을 간단한 CRUD로 시작할 예정입니다.
<br/>
=> ✨ 코드 추가 : 캠페인 템플릿 기능 개발 전 기본 세팅 추가

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/CouponDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
<br/>
- coupon 도메인 기능 구현을 위한 기본 세팅
<br/>
- coupon 도메인 조회 기능 구현
<br/>
=> feat(#14): Coupon 기본 세팅

LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/dto/AdminDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/entity/Admin.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/repository/AdminRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminService.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminServiceImpl.java
- 제목 : ✨ 기능 추가 : Admin Entity 및 DTO 관련 Service, Repository 기능 추가
<br/>
Admin Entity 및 DTO 관련 Service, Repository 기능 추가 하였습니다.
<br/>
<br/>
-Service 로직 구현하기 
<br/>
=> ✨ 기능 추가 : Admin Entity 및 DTO 관련 Service, Repository 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/MemberType.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/entity/Member.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestInsertMemberVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestSaveMemberVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseFindMemberVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/controller/ReportController.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/domain/dto/ReportDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/domain/entity/Report.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/domain/vo/request/RequestReportVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/domain/vo/response/ResponseReportVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/repository/ReportRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/service/ReposrtService.java
<br/>
flag가 true, memberType에 따른 조회기능 추가
report 기본세팅
<br/>
<br/>
블랙리스트 기본 세팅
멤버 상세조회
<br/>
close #24 
close #25
=> feat(#24, #25) MemberList 조회, Report 기본 세팅

LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistController.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/dto/BlacklistDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/entity/Blacklist.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/request/RequestBlacklistVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseBlacklistVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java
- 제목 : feat(#26 ): Blacklist 기본 세팅
<br/>
블랙리스트의 기본 세팅 구현
<br/>
<br/>
<br/>
close #26
=> ✨ 기능 추가 / 수정: Blacklist 기본 세팅 완료

LearnsMate/src/main/java/intbyte4/learnsmate/common/mapper/GenericMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/common/mapper/MemberMapper.java
- 제목 : feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
=> ✨ 기능 추가 / 수정: Mapper class 추가

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestInsertCampaignVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseInsertCampaignVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
- 제목 : feat(#3 ): RequestInsertCampaignVO,ResponseInsertCampaignVO 추가
<br/>
- 캠페인 등록 controller, 관련 VO 추가했습니다.
<br/>
<br/>
- 캠페인 조회 기능
<br/>
=> ✨ 기능 추가: RequestInsertCampaignVO,ResponseInsertCampaignVO 추가

LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/controller/CampaignTemplateController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/CampaignTemplate.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/dto/CampaignTemplateDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/vo/request/RequestEditTemplateVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/vo/request/RequestRegisterTemplateVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/vo/response/ResponseEditTemplateVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/vo/response/ResponseRegisterTemplateVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/mapper/CampaignTemplateMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignTemplateService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignTemplateServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java
<br/>
- 캠페인 템플릿 추가, 매퍼 수정했습니다.
- 매퍼에 대해서 잘 읽어보고 적용하는데 도움이 되셨으면 좋겠네요
<br/>
서비스 코드와 애플리케이션이 잘 실행되는 것을 확인할 수 있습니다.
<br/>
- 삭제 API 추가
<br/>
close #4
=> feat (#4) : 캠페인 템플릿 수정 API 추가

LearnsMate/src/main/java/intbyte4/learnsmate/common/mapper/GenericMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/common/mapper/MemberMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/entity/Member.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestSaveMemberVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseFindMemberVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
- 제목 : feat(#33 ): MemberMapper 생성
<br/>
<br/>
<br/>
<br/>
=> MemberMapper 생성

LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureFilterDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/Lecture.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/specification/LectureSpecifications.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/EditLectureInfoVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/enums/LectureCategory.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/enums/LectureLevel.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/LectureRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
- 제목 :  ✨ 기능 추가 : LectureSpecifications 동적 필터링 기능 추가
<br/>
강의 조회 시, 카테고리별 조회 필터링이 되야하므로 동적 필터링이 가능하게  LectureSpecifications 동적 필터링 기능 추가하였음
<br/>
<br/>
- 강사 명과 계약 승인 과정을 Join하여 service로직을 짜고, 도입 할 예정
<br/>
=> ✨ 기능 추가 : LectureSpecifications 동적 필터링 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/controller/CampaignTemplateController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/domain/vo/response/ResponseFindTemplateVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/mapper/CampaignTemplateMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignTemplateService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaigntemplate/service/CampaignTemplateServiceImpl.java
<br/>
- 캠페인 템플릿 전체 조회 기능 추가 및 Operation 추가
<br/>
커밋 내역 최신화 한 뒤 실행 잘 되는 것 확인했습니다.
<br/>
- 단 건 조회 추가
<br/>
=> feat(#42): 캠페인 템플릿 컨트롤러 - 전체 조회 기능 추가 및 Operation 추가

LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/controller/ReportController.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/repository/ReportRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/service/ReportService.java
- 제목 : feat(issue 번호): 기능명
<br/>
강사 코드로 강사명 찾아오는 메서드 추가했습니다.
<br/>
<br/>
<br/>
=> ✨ 기능 추가 / 수정: MemberService -> 강사코드로 강사명 찾아오는 서비스 메서드 작성

LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VocController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VocService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VocServiceImpl.java
<br/>
VocService에서 findByVocCode 코드를 수정했습니다.
<br/>
<br/>
<br/>
=> feat(#63 ): VOC - 서비스 매개변수 타입 변경

LearnsMate/src/main/java/intbyte4/learnsmate/voc/mapper/VocMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VocServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/domain/dto/VocCategoryDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/repository/VocCategoryRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/service/VocCategoryService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/service/VocCategoryServiceImpl.java
<br/>
엔티티 변환 추가 및 VOC 답변에서 사용하기 위한 VOC카테고리 서비스 코드 추가했습니다.
<br/>
<br/>
<br/>
=> Feature/voc : 엔티티 변환 추가 및 VOC 답변에서 사용하기 위한 VOC카테고리 서비스 코드 추가

LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/CouponDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/CouponRegisterRequestVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/CouponRegisterResponseVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
<br/>
- 쿠폰을 등록할 수 있도록 Service, Controller, Mapper, Entity, DTO, VO, Repository로 기능을 만들었습니다
<br/>
<br/>
- 쿠폰 조회, 수정, 삭제 기능을 구현할 예정입니다.
<br/>
=> feat(#7) 쿠폰 등록 기능

LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/controller/VocAnswerController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/VocAnswer.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/dto/VocAnswerDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/request/RequestRegisterVocAnswerVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseRegisterVocAnswerVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/mapper/VocAnswerMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/repository/VocAnswerRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VocAnswerService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VocAnswerServiceImpl.java
<br/>
VOC 답변 등록 기능 추가했습니다.
VOC와 Member, VocCategory 도 찾고, 등록 기능도 추가했습니다.
<br/>
<br/>
<br/>
close #59
=> feat(#59 ): VOC 답변 등록 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VocAnswerServiceImpl.java
<br/>
MemberService에서 findByStudentCode 메소드를 추가해 학생코드로 Member 조회 추가
<br/>
<br/>
- VOC 답변 조회, 수정, 삭제 기능 추가
<br/>
close #68
=> feat(#68 ): Member 학생코드로 Member 조회 추가

LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/response/ResponseFindVocVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/controller/VOCAnswerController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/VOCAnswer.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/dto/VOCAnswerDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/request/RequestEditVOCAnswerVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/request/RequestRegisterVOCAnswerVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseEditVOCAnswerVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseRegisterVOCAnswerVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/mapper/VOCAnswerMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/repository/VOCAnswerRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VocAnswerService.java
<br/>
VOC 수정 기능 추가를 하였고, Controller, Service, mapper에 추가, 응답, 요청 VO도 추가했습니다.
<br/>
<br/>
- VOC 클래스 명 리팩토링 + VOC 답변 삭제, 조회 기능 추가
<br/>
close #60
=> feat(#60  ): VOC 답변 수정 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/controller/CampaignTemplateController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/mapper/CampaignTemplateMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
<br/>
캠페인 템플릿 조회 반환형 수정했습니다.
<br/>
<br/>
<br/>
=> 캠페인 템플릿 조회 반환형 수정

LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/controller/VOCAnswerController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseFindVOCAnswerVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/mapper/VOCAnswerMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerServiceImpl.java
<br/>
VOC 답변 단 건 조회 반환형 전체적 수정했습니다.
<br/>
=> VOC 답변 단 건 조회 반환형 전체적 수정

LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/mapper/VOCMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
<br/>
VOC 조회 매개변수 반환형 전체 수정했습니다.
<br/>
=> ♻️ 코드 수정 : VOC 조회 매개변수 반환형 전체 수정

LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/controller/CampaignTemplateController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/mapper/CampaignTemplateMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/mapper/VOCMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/controller/VOCAnswerController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/mapper/VOCAnswerMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerServiceImpl.java
=> ♻️ 코드 수정 : 전체 코드 수정

LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/VOCAnswer.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/request/RequestEditVOCAnswerVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/request/RequestRegisterVOCAnswerVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseEditVOCAnswerVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseFindVOCAnswerVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseRegisterVOCAnswerVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerServiceImpl.java
<br/>
VOC 답변 등록 시 VOC의 답변 현황 True로 변경 기능 추가했습니다.
<br/>
close #77
=> feat(#77): VOC 답변 등록 시 VOC의 답변 현황 True로 변경 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java
<br/>
- 단 건 조회 controller 메서드명 수정
- entity의 table 어노테이션 주석 제거
<br/>
<br/>
- 필터 별 조회 기능 추가
<br/>
=> ♻️ 코드 수정: 단 건 조회 controller 메서드명 수정, table 어노테이션 주석 제거

LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/service/VocCategoryServiceImpl.java
=> ✨ 기능 수정 : VOC 카테고리 서비스 코드 수정

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/domain/CouponCategory.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/domain/dto/CouponCategoryDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/repository/CouponCategoryRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/service/CouponCategoryService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/service/CouponCategoryServiceImpl.java
<br/>
쿠폰 카테고리 엔터티를 추가하면서 Coupon 의 엔터티 수정 및 쿠폰 카테고리 관련 Service, Repository 추가했습니다.
<br/>
close #81
=> feat(#81): 쿠폰 카테고리 추가

LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistController.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseFindReservedStudentBlacklistVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/domain/vo/response/ResponseFindReservedTutorBlacklistVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/mapper/BlacklistMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/domain/dto/ReportedMemberDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/repository/ReportRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/service/ReportService.java
- 제목 : feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
<br/>
1. 신고 테이블에서 신고 5회 이상 당한 멤버(유저/강사) 가져오기 
-> 새로운 ReportedMemberDTO 생성(Member, Integer count)
2. 멤버 테이블과 비교해서 신고 5회 + flag가 true인 멤버 가져오기
3. 예비 블랙리스트에 추가
<br/>
<br/>
블랙리스트 등록
<br/>
=> ✨ 기능 추가 / 수정: 신고 5회 이상 당한 사람 예비 블랙리스트로 보여주는 로직 구현

LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/entity/Member.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestEditMemberVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
- 제목 : feat(#84 ): 기능명 - 회원정보 수정, 삭제 메서드 추가
<br/>
회원정보 수정, 삭제 메서드 추가
<br/>
<br/>
멤버쪽 추가 메서드 작성
<br/>
=> ✨ 기능 추가 / 수정: 회원정보 수정, 삭제 메서드 추가

LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
- 제목 : feat(#88 ): 기능명 ✨ 기능 추가 / 수정: 학생 단건 조회, 강사 단건 조회 추가
<br/>
✨ 기능 추가 / 수정: 학생 단건 조회, 강사 단건 조회 추가
<br/>
단건 조회시 쿠폰, voc, 강의 등 많은 데이터를 가져와야하기 때문에 추후 다른 도메인 서비스 메서드 추가 예정
<br/>
close #88
=> ✨ 기능 추가 / 수정: 학생 단건 조회, 강사 단건 조회 추가

LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/CampaignTemplate.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/vo/request/RequestRegisterTemplateVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/vo/response/ResponseEditTemplateVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/mapper/CampaignTemplateMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
<br/>
등록, 수정 관련 메소드 분리를 하였고, 엔티티 일관성을 위해 수정했습니다.
그리고 필요한 데이터만 사용하기 위해 VO도 수정했습니다.
<br/>
<br/>
- IssueCoupon 관련 API 추가
<br/>
=> 캠페인 템플릿 코드 수정

LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/domain/CouponCategory.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/IssueCoupon.java
=> issueCoupon 엔티티 일관성을 위해 수정

LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/IssueCoupon.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/dto/IssueCouponDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/vo/response/IssueCouponFindResponseVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/mapper/IssueCouponMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/IssueCouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
feat(#96 ): 학생이 자신에게 발급된 쿠폰볼 수 있는 조회 기능 추가
<br/>
쿠폰의 활성화 여부를 보고 학생이 자신에게 발급된 쿠폰을 조회할 수 있게 추가했습니다.
<br/>
<br/>
<br/>
close #96
=> feat(#96 ): 학생이 자신에게 발급된 쿠폰볼 수 있는 조회 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/IssueCoupon.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/dto/IssueCouponDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/vo/response/IssueCouponRegisterResponseVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/vo/response/IssueCouponUseResponseVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/mapper/IssueCouponMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/IssueCouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
<br/>
학생 쿠폰 사용 시 수정 코드 추가했습니다.
<br/>
=> feat(#103 ): 학생 쿠폰 사용 시 수정 코드 추가

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignCouponVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/domain/dto/CouponByCampaignDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/mapper/CouponByCampaignMapper.java
- 제목 :  CouponByCampaignDTO -> 컬럼명 수정, 타입 변경
<br/>
- 카멜케이스 오타, 타입 String -> Long 변경
<br/>
<br/>
- 제목으로 조회
<br/>
=> ♻️ 코드 수정: CouponByCampaignDTO -> 컬럼명 수정, 타입 변경

LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/dto/AdminDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/entity/Admin.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/request/RequestEditAdminVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/response/ResponseEditAdminVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/response/ResponseFindAdminVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/mapper/AdminMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminService.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerServiceImpl.java
- 제목 : feat:  AdminController 직원 정보 수정 Controller 기능 추가
<br/>
AdminMapper 클래스를 추가하여 dto및 entity 타입변환 수정하였습니다.
또한 AdminController 직원 정보 수정 Controller 기능 추가하였습니다.
<br/>
<br/>
- 필요한 admin쪽 Service 메소드 찾기 및 비밀번호 재설정 기능을 구현해야합니다. ( 닭경석씨와 같이 )
<br/>
=> ✨ 기능 추가 : AdminController 직원 정보 수정 Controller 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistController.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java
- 제목 : feat(#106 ): 기능명 ✨ 기능 추가 / 수정: 학생, 강사 블랙리스트 단건 조회 추가
<br/>
✨ 기능 추가 / 수정: 학생, 강사 블랙리스트 단건 조회 추가 -> 예비 블랙리스트 단건 조회의 서비스를 같이 사용했습니다.
그로 인해 서비스명이 수정되었습니다.
<br/>
멤버에서 파생되는 2개의 테이블 생성 및 서비스 작성
<br/>
close #106
=> ✨ 기능 추가 / 수정: 학생, 강사 블랙리스트 단건 조회 추가

LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/request/RequestEditAdminVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/response/ResponseEditAdminVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/response/ResponseFindAdminVO.java
- 제목 : feat: ✨ 기능 추가 :JsonNaming 스네이크 케이스로 변환 기능 수정
<br/>
@JsonNaming 어노테이션을 사용하면 각 필드에 일일이 @JsonProperty 어노테이션을 달지 않아도 되므로, 코드가 더 깔끔하고 효율적으로 처리된다고 하여 수정하였습니다.
<br/>
<br/>
- 로그인 재설정 및 직원부분 필요한 service코드 찾기
<br/>
=> ✨ 기능 추가 :JsonNaming 스네이크 케이스로 변환 기능 수정

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestRegisterCampaignVO.java
- 제목 : feat(#92 , #99 ): @RequestBody 중복 삭제
<br/>
- @RequestBody 중복 사용한 부분 수정했습니다.
<br/>
<br/>
- 제목으로 조회, 기간으로 조회, 타입별 조회
<br/>
=> ♻️ 코드 수정: CampaignController -> @RequestBody 중복 삭제

LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecturebystudent/service/LectureByStudentServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/login_history/controller/LoginHistoryController.java, LearnsMate/src/main/java/intbyte4/learnsmate/login_history/domain/entity/LoginHistory.java, LearnsMate/src/main/java/intbyte4/learnsmate/login_history/domain/vo/request/RequestSaveLoginHistoryVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/login_history/domain/vo/response/ResponseFindLoginHistoryVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/login_history/mapper/LoginHistoryMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/login_history/repository/LoginHistoryRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/login_history/service/LoginHistoryService.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
- 제목 : feat(#116 #117  ): 기능명 ✨ 기능 추가 / 수정: 로그인 내역 조회, 추가, 수정
<br/>
로그인 내역 전체 조회, 단일 조회
특정 멤버의 전체 로그인 내역 조회
로그인 내역에 추가
로그아웃 시간 추가(수정)
<br/>
특정 시간대의 로그인 내역만 가져오는 메서드 생각중입니다.
<br/>
close #116 #117
=> ✨ 기능 추가 / 수정: 로그인 내역 조회, 추가, 수정

LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/repository/CouponByLectureRepository.java
=> ♻️ 코드 수정 : 강의 별 쿠폰 조회 쿼리 수정

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/TutorCouponRegisterRequestVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
<br/>
- 강사 쿠폰 등록 기능 추가
<br/>
<br/>
- 쿠폰 수정, 삭제 기능 추가
<br/>
=> feat(#7): 직원 쿠폰 등록

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/AdminCouponRegisterRequestVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
<br/>
직원 쿠폰 등록 기능 추가
<br/>
<br/>
- 직원의 쿠폰 수정, 삭제 기능 추가
<br/>
close #127 #
=> feat(#127): 직원 쿠폰 등록 기능

LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/controller/PreferredTopicsController.java, LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/domain/dto/PreferredTopicsDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/domain/entity/PreferredTopics.java, LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/domain/vo/request/RequestSavePreferredHistoryVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/domain/vo/response/ResponseFindPreferredTopicsVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/mapper/PreferredTopicsMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/repository/PreferredTopicsRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/service/PreferredTopicsService.java
- 제목 : feat(#124 #125 ): 기능명 ✨ 기능 추가 / 수정: 선호 주제 리스트 조회, 등록 메서드, 추가
<br/>
멤버의 선호주제를 조회, 등록하는 메서드를 구현했습니다.
<br/>
삭제 메서드 추가 논의, 강의별 강의 카테고리 구현
<br/>
=> ✨ 기능 추가 / 수정: 선호 주제 리스트 조회, 등록 메서드, 추가

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
<br/>
직원 쿠폰 수정 시 직원 validation 코드 추가
<br/>
<br/>
- 직원 쿠폰 삭제 기능 추가
<br/>
=> 직원 쿠폰 수정 시 직원 validation 코드 추가

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
<br/>
직원 코드 삭제 기능 추가했습니다. 실제로 있는 직원인지도 확인하는 코드도 함께 추가했습니다.
<br/>
<br/>
<br/>
close #133
=> feat(#133): 직원 코드 삭제 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/controller/ContractProcessController.java, LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/domain/vo/request/ResponseRegisterContractProcessVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/domain/vo/response/RequestRegisterContractProcessVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/domain/vo/response/ResponseFindContractProcessVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/mapper/ContractProcessMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/repository/ContractProcessRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/service/ContractProcessService.java, LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/service/ContractProcessServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
- 제목 : feat: ✨ 기능 수정 : registerLecture Service 기능 수정
<br/>
-  강의별 계약과정 조회 ✅
-  강의별 계약과정 등록 메소드 만들기 ✅
-  강의별 계약과정이 등록할때 같은 강의 코드와 같은 ApprovalProcess의 값이 존재 한다면 ? 예외처리 ✅
-  강의 등록 메소드 만들기 ✅
<br/>
<br/>
- -  강의 등록 메소드에  강의별 동영상 등록 -> 강의별 카테고리 등록 메소드 포함하기 
<br/>
=> ✨ 기능 수정 : registerLecture Service 기능 수정

LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
<br/>
특정 고객의 VOC에 대해 미답변, 답변에 따라 조회할 수 있게 추가했습니다.
<br/>
<br/>
<br/>
=> 특정 고객의 VOC에 대해 미답변, 답변에 따라 조회할 수 있게 추가

LearnsMate/src/main/java/intbyte4/learnsmate/config/GptConfig.java
<br/>
GptConfig 추가했습니다. 분석을 위해 추가해야 할 것 같아요!
<br/>
<br/>
- GPT로 분석하는 프롬프팅을 진행하고, 프론트엔드를 할 예정입니다.
<br/>
=> ✨ 기능 추가 : GptConfig 추가

LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/CouponDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/TutorCouponEditRequestVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/TutorCouponEditResponseVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java
<br/>
- 강사 쿠폰 삭제 및 강사 쿠폰 활성화, 비활성화 상태 변경
<br/>
<br/>
- 사용 쿠폰 및 미사용 쿠폰 조회 기능
<br/>
closes #7 
closes #140
=> feat(#7, #140): 쿠폰 삭제 (강사), 강사 쿠폰 활성화, 비활성화 상태 변경

LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/contractprocess/service/ContractProcessServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/Lecture.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/request/RequestEditLectureInfoVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/request/RequestRegisterLectureVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseEditLectureInfoVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseFindLectureVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseRegisterLectureVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseRemoveLectureVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/controller/LectureCategoryByLectureController.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/domain/dto/LectureCategoryByLectureDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/domain/dto/OneLectureCategoryListDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/domain/entity/LectureCategoryByLecture.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/domain/vo/response/ResponseFindLectureCategoryByLectureVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/mapper/LectureCategoryByLectureMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/repository/LectureCategoryByLectureRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java, LearnsMate/src/main/java/intbyte4/learnsmate/login_history/controller/LoginHistoryController.java, LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/controller/PreferredTopicsController.java, LearnsMate/src/main/java/intbyte4/learnsmate/video_by_lecture/service/VideoByLectureServiceImpl.java
- 제목 : feat(issue 번호): 기능명 ✨ 기능 추가 / 수정: 특정 강의별 강의 카테고리 코드로 조회하는 메서드 추가
<br/>
강의별 강의 카테고리 엔티티 구현 + 강의 엔티티 수정
<br/>
<br/>
<br/>
=> ✨ 기능 추가 / 수정: 특정 강의별 강의 카테고리 코드로 조회하는 메서드 추가

LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/video_by_lecture/service/VideoByLectureServiceImpl.java
- 제목 : feat: ✨ 기능 수정 :  Lecture 기능 수정
<br/>
- Lecture 기능 수정
<br/>
<br/>
- .순환참조 잠시 해결
<br/>
=> ✨ 기능 수정 :  Lecture 기능 수정

LearnsMate/build.gradle, LearnsMate/src/main/java/intbyte4/learnsmate/excel/controller/ExcelController.java, LearnsMate/src/main/java/intbyte4/learnsmate/excel/service/ExcelService.java
<br/>
엑셀 다운로드/업로드를 위한 의존성 추가, 컨트롤러 서비스 추가
<br/>
<br/>
<br/>
=> 엑셀 다운로드/업로드를 위한 의존성 추가, 컨트롤러 서비스 추가

LearnsMate/src/main/java/intbyte4/learnsmate/facade/MemberCouponFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
<br/>
퍼사드 패턴 적용해서 발급 쿠폰, 학생 별 순환참조 해결해봤습니다.
<br/>
=> 발급 쿠폰, 학생 별 순환참조 해결을 위한 퍼사드 패턴 적용

LearnsMate/src/main/java/intbyte4/learnsmate/facade/MemberCouponFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/IssueCouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
<br/>
쿼리 메소드 수정을 통해 Member 엔티티의 올바른 필드로 연결했습니다.
<br/>
=> 발급 쿠폰 쿼리 메소드 수정

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/facade/CouponLectureFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/facade/MemberCouponFacade.java
<br/>
쿠폰과 강의의 순환참조 해결을 위한 퍼사드 패턴 적용했습니다.
<br/>
=> 쿠폰과 강의의 순환참조 해결을 위한 퍼사드 패턴 적용

LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/IssueCouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/FindSingleMemberDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberIssueCouponDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberVOCDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseFindMemberDetailVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
- 제목 : feat(#150 ): 기능명 ✨ 기능 추가 / 수정: 멤버 상세 조회 메서드 이동 및 수정 및 추가
<br/>
순환참조 없애기 위해 그리고 서비스 역할을 명확히 하기 위해 MemberFacade 생성 및 단일 조회 메서드 ㅇ이동
<br/>
순환참조 제거
<br/>
=> ✨ 기능 추가 / 수정: 멤버 상세 조회 메서드 이동 및 수정 및 추가

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/facade/LectureFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/mapper/IssueCouponMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/mapper/LectureByStudentMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/repository/LectureByStudentRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category/service/LectureCategoryService.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/RequestRegisterPaymentVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/ResponseRegisterPaymentVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentService.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
- 제목 : feat(#151 ): lecturePayment 추가
<br/>
- 결제 후 학생별 강의, 결제, 학생별 강의 동영상이 등록 되어야 한다.
<br/>
<br/>
- LecturePayment Controller 추가
<br/>
=> ✨ 기능 추가: PaymentService -> lecturePayment 추가

LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureDetailDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/Lecture.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/domain/dto/LectureByStudentDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/domain/entity/LectureByStudent.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/mapper/LectureByStudentMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/repository/LectureByStudentRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/repository/LectureCategoryByLectureRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/dto/PaymentDetailDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
- 제목 : feat ✨ 기능 추가 : 강의 코드에 해당하는 결제 금액을 합산 쿼리 기능 추가
<br/>
-  강의 코드에 해당하는 결제 금액을 합산 쿼리 기능 추가
<br/>
<br/>
- 강의 퍼사드 서비스 활용 리팩토링 
<br/>
=> ✨ 기능 추가 : 강의 코드에 해당하는 결제 금액을 합산 쿼리 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/facade/LectureFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseFindLectureVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java
- 제목 : feat: ✨ 기능 추가 : LectureService <=> LectureFacade 코드 리팩 토링 및 DTO 통합 반환 기능 추가
<br/>
LectureService <=> LectureFacade 코드 리팩 토링 및 DTO 통합 반환 기능 추가
<br/>
<br/>
- 필터링 조회 (세팅만 완료)  -> 쿼리dsl로 적용하기
<br/>
=> ✨ 기능 추가 : LectureService <=> LectureFacade 코드 리팩 토링 및 DTO 통합 반환 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/facade/LectureFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/facade/PaymentFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentController.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/dto/PaymentDetailDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/ResponseFindPaymentVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/mapper/PaymentMapper.java
- 제목 : feat: ✨ 기능 추가 : PaymentFacade 전체 조회 및 단건조회 PaymentDetailDTO 반환 기능 추가
<br/>
- 직원이 전체 결제 내역을 조회 ✅ 
- 직원이 특정 결제 내역을 단건 상세 조회 ✅
+ 강의코드, 강의명, 강의 카테고리, 강사코드, 강사명, 학생코드, 학생명 , 강의 원가 + 적용 쿠폰코드+ 쿠폰 명+ 결제금액 + 결제일 ✅
<br/>
<br/>
- 필터링 조회 (세팅만 완료)  -> 쿼리dsl로 적용 (서짱에게 배우기) -> 젠짱이 도와준대 @@!!!!!
난이도 및 강의 카테고리 enum 추가하기 
<br/>
=> ✨ 기능 추가 : PaymentFacade 전체 조회 및 단건조회 PaymentDetailDTO 반환 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/facade/PaymentFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentService.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
<br/>
결제 전체, 단 건 조회 기능 수정했습니다.
<br/>
=> 결제 전체, 단 건 조회 기능 수정

LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberFilterRequestDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestFilterStudentVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestFilterTutorVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryCustom.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
- 제목 : feat(#171 ): 기능명 ✨ 기능 추가 / 수정: 학생, 강사 필터링 추가
<br/>
학생, 강사 필터링 조건을 통한 조회 기능을 구현
<br/>
<br/>
다른 도메인 필터링 추가
<br/>
close #171
=> ✨ 기능 추가 / 수정: 학생, 강사 필터링추가

LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
<br/>
quarydsl 로 만든 필터링 기능에 대해 서비스, 컨트롤러 코드를 추가했습니다.
=> VOC 필터링 서비스, 컨트롤러 코드 추가

LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/response/ResponseCountByCategoryVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/service/VocCategoryService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_category/service/VocCategoryServiceImpl.java
- 제목 : feat(#191 ): countVOCByCategory 추가
<br/>
- voc 카테고리 별로 voc 개수를 조회할 수 있습니다.
<br/>
<br/>
<br/>
=> ✨ 기능 추가: VOCService -> countVOCByCategory 추가

LearnsMate/src/main/java/intbyte4/learnsmate/common/config/WebConfig.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
<br/>
프론트엔드 배포로 인해 api 요청 응답을 위해 추가했습니다.
<br/>
=> ✨ 기능 수정 : WebConfig 수정, VOC api cors 추가

.github/workflows/deploy.yml
<br/>
jwt 추가로 인해 생기는 yml 관련 빌드 문제를 해결해봤습니다.
<br/>
=> ✨ 기능 수정 : deploy.yml 수정

LearnsMate/src/main/java/intbyte4/learnsmate/security/JwtUtil.java
<br/>
502 gateway 오류 수정을 위해 JwtUtil 수정을 해봤습니다.
<br/>
<br/>
<br/>
=> ✨ 기능 수정 : JwtUtil 수정

LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/vo/request/RequestLoginVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/repository/AdminRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/AdminServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/AuthenticationFilter.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
<br/>
✨기능 추가/수정: webSecurity 로그인 처리 수정
<br/>
api 연동
<br/>
=> ✨기능 추가/수정: webSecurity 로그인 처리 수정

LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberPageResponse.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryCustom.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
- 제목 : feat(#217 #218 ): 
<br/>
멤버 페이지네이션, 멤버 필터 페이지네이션 적용
<br/>
블랙리스트 페이지네이션
<br/>
=> 멤버 페이지네이션 추가

LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/repository/LectureCategoryByLectureRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/CategoryCountDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/entity/Member.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/pagination/MemberPageResponse.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/pagination/MemberPageResponseWithGraph.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/CategoryRatioFilterRequest.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/CategoryRatioResponse.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
<br/>
유저 전체 조회 offset, cursor 방식 추가
기간 별 카테고리 별 학생들이 구매한 강의 비율 구하는 서비스 코드 추가 (특정 기간 선택 가능)
<br/>
<br/>
<br/>
=> 유저 전체 조회 offset, cursor 방식 추가 및 기간 별 카테고리 별 학생들이 구매한 강의 비율 구하는 서비스 코드 추가 (특정 기간 선택 가능)

LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/dto/VOCCategoryCountDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/request/VOCCategoryRatioFilterRequest.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
<br/>
VOC 카테고리 별 개수 구하는 API 추가 및 특정 기간으로 필터링 API 추가했습니다.
<br/>
=> VOC 카테고리 별 개수 구하는 API 추가 및 특정 기간으로 필터링 API 추가

LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentController.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/dto/PaymentMonthlyRevenueDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/domain/vo/PaymentPageResponse.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/repository/PaymentRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentFacade.java
<br/>
결제 전년도 데이터와 함께 월별로 비교 및 전체 조회 api 추가했습니다.
=> 결제 전년도 데이터와 함께 월별로 비교 및 전체 조회 api 추가

LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCExcelController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/dto/VOCFilterRequestDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepositoryCustom.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCExcelService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
<br/>
VOC 액셀 다운로드할 때 컬럼 순서 적용 추가 및 필터링 적용했습니다.
<br/>
=> VOC 액셀 다운로드할 때 컬럼 순서 적용 추가 및 필터링 적용

LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/domain/vo/response/ResponseFindVOCVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/mapper/VOCMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/controller/VOCAnswerController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/request/RequestRegisterVOCAnswerVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/domain/vo/response/ResponseRegisterVOCAnswerVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/mapper/VOCAnswerMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc_answer/service/VOCAnswerServiceImpl.java
<br/>
voc 답변 등록, 수정 api 프론트엔드 연동 완료했고 관련 기능 추가 및 수정했습니다.
<br/>
=> voc 답변 등록, 수정 api 프론트엔드 연동 완료

LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureExcelController.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureFilterDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/LectureLevelEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/LecturePageInfo.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseFindLectureVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/pagination/LectureCursorPaginationResponse.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/LectureRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureExcelService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category/domain/entity/LectureCategoryEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/repository/LectureCategoryByLectureRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java
<br/>
✨ 기능 추가 : lecture 전체 조회 데이터 확인, 필터링 기능 프론트엔드 연동 확인
=> ✨ 기능 추가 : lecture 전체 조회 데이터 확인, 필터링 기능 프론트엔드 연동 확인

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/FindAllCampaignsDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/FindCampaignDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseFindCampaignVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/CouponDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/repository/CouponByCampaignRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/service/CouponByCampaignService.java, LearnsMate/src/main/java/intbyte4/learnsmate/couponbycampaign/service/CouponByCampaignServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java, LearnsMate/src/main/java/intbyte4/learnsmate/userpercampaign/repository/UserPerCampaignRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/userpercampaign/service/UserPerCampaignService.java, LearnsMate/src/main/java/intbyte4/learnsmate/userpercampaign/service/UserPerCampaignServiceImpl.java
- 제목 : feat(issue 번호): ✨ 기능 수정: 캠페인 삭제 수정
- [ x] BE
<br/>
- 캠페인 삭제할 때 userPerCampaign, couponByCampaign이 먼저 삭제되어야 하는데 campaign만 삭제해서 문제가 있었습니다.
<br/>
<br/>
<br/>
=> ✨ 기능 수정: 캠페인 삭제 수정

LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/LectureStatsFilterDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/dto/MonthlyLectureFilterDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/LectureStatsVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseFindLectureDetailVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/LectureRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/repository/LectureCategoryByLectureRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/service/LectureCategoryByLectureService.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/repository/PaymentRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentService.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java
<br/>
lecture 월별 데이터 조회 관련 데이터 + 필터링 기능 추가, 단 건 조회 시 구매 전환율 데이터 특정 기간 필터링 기능 추가, 수정했습니다.
<br/>
=> lecture 월별 데이터 조회 관련 데이터 + 필터링 기능 추가, 단 건 조회 시 구매 전환율 데이터 특정 기간 필터링 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberExcelController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/FindSingleStudentDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseFindMemberVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseFindStudentDetailVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryCustom.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberExcelService.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
<br/>
회원 엑셀 다운로드 기능 추가
<br/>
엑셀 업로드, 블랙리스트 엑셀 다운로드 적용
<br/>
=> ✨ 기능 추가 / 수정: 회원 엑셀 다운로드 완료

LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistExcelController.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepositoryCustom.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistExcelService.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java, LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_by_student/service/LectureByStudentServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/domain/entity/LectureCategoryByLecture.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture_video_by_student/service/LectureVideoByStudentServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/login_history/domain/entity/LoginHistory.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberExcelController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/entity/Member.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryCustom.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberExcelService.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/preferred_topics/domain/entity/PreferredTopics.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/domain/entity/Report.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
<br/>
✨기능 추가: 블랙리스트 엑셀 다운르도, 학생 엑셀 업로드 추가
<br/>
데이터 분석
<br/>
=> ✨기능 추가: 블랙리스트 엑셀 다운르도, 학생 엑셀 업로드 추가

LearnsMate/src/main/java/intbyte4/learnsmate/lecture_category_by_lecture/repository/LectureCategoryByLectureRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/CategoryStatDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java
<br/>
✨기능 추가: 회원 카테고리별 학생 수 분석 데이터 수정
<br/>
회원 서비스 회원가입 로그인 구현
<br/>
=> ✨기능 추가: 회원 카테고리별 학생 수 분석 데이터 수정

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignExcelController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignFilterDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/FindCampaignDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepositoryCustom.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignExcelService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberExcelController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberExcelService.java
- 제목 : feat(#243 #242 ): importTargetStudentFromExcel 추가
<br/>
- 엑셀 업로드 - 타겟 유저 ✅
- 엑셀 다운로드 - 캠페인 ✅
<br/>
<br/>
- 유효하지 않은 데이터가 업로드 될 경우 모달창 뜨게 하기
<br/>
=> ✨ 기능 추가: MemberExcelService -> importTargetStudentFromExcel 추가

LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/controller/CampaignTemplateController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/dto/FindCampaignTemplateDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/mapper/CampaignTemplateMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
- 제목 : feat(issue 번호): getTemplate 수정
<br/>
- 캠페인 템플릿 단건 조회시 담당자 이름도 조회되도록 변경했습니다.
<br/>
<br/>
<br/>
=> ♻️코드 수정: CampaignTemplateController ->getTemplate 수정

LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
- 제목 : WebSecurity HttpSecurity 설정 추가
<br/>
<br/>
<br/>
<br/>
=> ✨기능 추가: WebSecurity HttpSecurity 설정 추가

LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
- 제목 : feat(issue 번호): ✨ 기능 추가 : 직원 로그아웃 Controller 기능 추가
<br/>
직원 로그아웃 Controller 기능 추가하였습니다.
<br/>
<br/>
- 비밀번호 이메일 인증 재설정 구현하기
<br/>
=> ✨ 기능 추가 : 직원 로그아웃 Controller 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/client/controller/ClientController.java, LearnsMate/src/main/java/intbyte4/learnsmate/client/domain/dto/ClientLoginDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/client/domain/dto/ClientLoginHistoryDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/client/service/ClientService.java, LearnsMate/src/main/java/intbyte4/learnsmate/login_history/service/LoginHistoryService.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestLoginVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/request/RequestLogoutVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseLoginVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/mapper/MemberMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
- 제목 : feat(#258 #257):
<br/>
로그인시 로그인이력 테이블에 저장하고 로그아웃시 업데이트하는 로직 추가
회원 로그인 구현
<br/>
<br/>
=> ✨기능 추가: 회원 로그인, 로그아웃 로그인 이력 추가

LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/AuthenticationFilter.java
- 제목 : feat: ✨ 기능 추가 : 직원 사번, 부서 정보 추출 기능 추가
<br/>
해당 로그인 직원 정보 기능 추가
<br/>
<br/>
-비밀번호 이메일 인증 재설정 구현하기
<br/>
=> ✨ 기능 추가 : 직원 사번, 부서 정보 추출 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignExcelService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/controller/CampaignTemplateExcelController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/mapper/CampaignTemplateMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepositoryCustom.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateExcelService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
- 제목 : feat(#268 ): CampaignTemplateExcelController추가
<br/>
- 캠페인 템플릿 조건에 따른 엑셀 파일 다운로드가 가능합니다.
<br/>
<br/>
<br/>
=> ✨기능 추가: CampaignTemplateExcelController추가

LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryImpl.java
✨기능 추가: member, blacklist 조회시 code DESC로 하게 수정
<br/>
✨기능 추가: member, blacklist 조회시 code DESC로 하게 수정
<br/>
필요컬럼 선택 추가
<br/>
=> ✨기능 추가: member, blacklist 조회시 code DESC로 하게 수정

LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/dto/MemberFilterRequestDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberExcelService.java
<br/>
✨기능 추가: 엑셀 컬럼 지정 다운로드 추가
<br/>
=> ✨기능 추가: 엑셀 컬럼 지정 다운로드 추가

LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberExcelService.java
<br/>
✨기능 추가: 엑셀 컬럼 지정 다운로드 수정
=> ✨기능 추가: 엑셀 컬럼 지정 다운로드 수정

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/RegisterCouponDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/AdminCouponRegisterRequestVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/LectureRequestVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon_by_lecture/domain/CouponByLecture.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/domain/dto/CouponCategoryEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/repository/CouponCategoryRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/service/CouponCategoryService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon_category/service/CouponCategoryServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/Lecture.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/entity/LectureLevelEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseFindLectureVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java
<br/>
- 직원 쿠폰 등록 로직이 잘못되어 수정했습니다
<br/>
<br/>
- 프론트
<br/>
=> ♻️ 코드 수정 : 직원 쿠폰 등록 로직 수정

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignFilterDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignExcelService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/controller/CampaignTemplateExcelController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/domain/dto/CampaignTemplateFilterDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateExcelService.java
- 제목 : feat(issue 번호): exportCampaignToExcel 수정
<br/>
- exportCampaignToExcel 수정
<br/>
<br/>
<br/>
=> ♻️코드 수정: exportCampaignToExcel 수정

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/AdminCouponEditRequestVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/TutorCouponEditRequestVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/request/TutorCouponRegisterRequestVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/TutorCouponEditResponseVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponServiceImpl.java
<br/>
쿠폰 컨트롤러에 바디에 안담기는 부분 모두 수정
RequestParam으로 받는데 PathVariable로 받는 부분 모두 후자로 수정
<br/>
=> ✨♻️기능 추가, 수정, 코드 수정: 쿠폰 컨트롤러 파라미터 수정 및 쿠폰 발급 서비스 추가

LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/RedisService.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/AuthenticationFilter.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/JwtFilter.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
- 제목 : feat: ✨ 기능 추가 :RedisService logout시 쿠키 삭제 및 redis 삭제 기능 추가
<br/>
로그아웃시 토큰 삭제 및 레디스 리프레시 토큰 삭제 
<br/>
<br/>
- 프론트랑 api연동 
<br/>
=> ✨ 기능 추가 :RedisService logout시 쿠키 삭제 및 redis 삭제 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/AdminController.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/TokenController.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/service/RedisService.java
- 제목 : feat: ✨ 기능 추가 : redis 리프레시 토큰 및 엑세스토큰 영구 삭제 기능 추가
<br/>
redis 리프레시 토큰 및 엑세스토큰 영구 삭제 기능 추가
<br/>
<br/>
-프론트와 api연동
<br/>
=> ✨ 기능 추가 : redis 리프레시 토큰 및 엑세스토큰 영구 삭제 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponExcelController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/CouponFilterDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/entity/CouponEntity.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/pagination/CouponPageResponse.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponExcelService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/controller/ReportController.java
- 제목 : feat(#283 #284 #285 ): 
<br/>
✨기능 추가: 쿠폰 조회, 필터링 조회 offset 페이지네이션 적용, 쿠폰 엑셀 업로드 추가
<br/>
멤버 그래프 수정
<br/>
=> ✨기능 추가: 쿠폰 조회, 필터링 조회 offset 페이지네이션 적용, 쿠폰 엑셀 업로드 추가

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponExcelService.java
<br/>
- 쿠폰 엑셀 다운로드 시 필터링 적용되도록 수정
<br/>
<br/>
- 쿠폰 등록 시 강의 조회 필터링 추가
<br/>
=> ♻️ 코드 수정 : 쿠폰 필터 조건 적용되도록 수정

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/common/config/EmailConfig.java, LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java
- 제목 : feat(#297 ): scheduleCampaigns 수정
<br/>
- 캠페인 예약 등록시 이슈쿠폰테이블에 바로 데이터가 insert되는 문제가 있어서 해결했습니다.
<br/>
<br/>
<br/>
=> ♻️코드 수정: scheduleCampaigns 수정

LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponExcelController.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/dto/IssuedCouponFilterDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/domain/pagination/IssueCouponPageResponse.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/CustomIssueCouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/CustomIssueCouponRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/IssueCouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponExcelService.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponFacade.java
- 제목 : feat(#299 #300 )
<br/>
✨기능 추가: 발급쿠폰 엑셀 다운로드, 발급 쿠폰 페이지네이션 추가 
<br/>
쿠폰 엑셀 업로드 도와주기
<br/>
=> ✨기능 추가: 발급쿠폰 엑셀 다운로드, 발급 쿠폰 페이지네이션 추가 

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponExcelController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/CouponFindResponseVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponExcelService.java
- 제목 : feat(issue 번호): importTargetCouponFromExcel 수정
<br/>
-  importTargetCouponFromExcel 수정
<br/>
<br/>
<br/>
=> ♻️코드 수정: importTargetCouponFromExcel 수정

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/CampaignFilterDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/FindAllCampaignsDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/dto/FindCampaignDetailDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignStudentVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestEditCampaignVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestFindCampaignByFilterVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestRegisterCampaignVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseEditCampaignVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseFindCampaignByFilterVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseFindCampaignDetailVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseFindCampaignVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/response/ResponseRegisterCampaignVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
- 제목 : feat(issue 번호):  campaignSendFlag 추가
<br/>
<br/>
<br/>
<br/>
=> ♻️코드 수정: campaignSendFlag 추가

LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/controller/ContractStatusController.java, LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/repository/ContractStatusRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/service/ContractStatusService.java, LearnsMate/src/main/java/intbyte4/learnsmate/contract_status/service/ContractStatusServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
- 제목 : feat(issue 번호): getApprovalProcessByLectureCode List로 반환
<br/>
<br/>
<br/>
<br/>
=> ♻️코드 수정: getApprovalProcessByLectureCode List로 반환

LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/MemberCountResponse.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/domain/vo/response/ResponseMemberCountVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
- 제목 : feat(#309 ): getMemberCount 추가
<br/>
-  전날 가입한 학생/강사 수, 전체 학생/강사 수 조회
<br/>
<br/>
<br/>
=> ✨기능 추가: MemberController -> getMemberCount 추가

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/dto/ClientFindCouponDTO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/domain/vo/response/ResponseClientFindCouponVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/mapper/CouponMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/domain/vo/response/ResponseClientFindLectureVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java
- 제목 : feat(#317 #318 ): 
<br/>
✨기능 추가: 강사 - 본인의 강의, 본인이 등록한 쿠폰 조회 메서드 추가
<br/>
마스킹
<br/>
=> ✨기능 추가: 강사 - 본인의 강의, 본인이 등록한 쿠폰 조회 메서드 추가

LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/TokenController.java, LearnsMate/src/main/java/intbyte4/learnsmate/admin/domain/entity/CustomUserDetails.java, LearnsMate/src/main/java/intbyte4/learnsmate/common/config/WebConfig.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
- 제목 : feat: ✨ 기능 추가 : efreshToken을 추출 후 set기능 추가
<br/>
refreshToken을 추출 후 set기능 추가하여  기존의 엑세스 토큰이 만료 되지 않았더라고 기존의 것을 덮어쓰는방식으로 리프레시 토큰을 활용해 엑세스 토큰 재발급 구현을 온료하였습니다.
<br/>
<br/>
- 전체적인 css 정리하기 
<br/>
=> ✨ 기능 추가 : 쿠키에서 refreshToken을 추출 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
<br/>
- 쿠폰 등록 시 강의 필터링 기능 추가
<br/>
<br/>
- css 통일
<br/>
=> ♻️ 코드 수정 : 쿠폰 등록 시 강의 필터링 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepositoryImpl.java
<br/>
- 쿠폰 활성화 필터 적용 안되는 현상 수정
<br/>
<br/>
- css 수정
<br/>
=> ♻️코드 수정: 쿠폰 활성화 필터 적용 안되는 현상 수정

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java
<br/>
- 쿠폰 조회 시 생성일 기준으로 내림차순 되도록 수정
<br/>
<br/>
- 기능 테스트
<br/>
=> ♻️코드 수정: 쿠폰 전체 조회 시 생성일 기준 내림차순 정렬 적용

LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/controller/BlacklistController.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepositoryCustom.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/repository/BlacklistRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/blacklist/service/BlacklistService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/mapper/LectureMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/repository/ReportRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/report/service/ReportService.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
<br/>
✨ 기능 추가 / 수정: Student, tutor, blacklist sort 기능 추가
<br/>
=> ✨ 기능 추가 / 수정: Student, tutor, blacklist sort 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/lecture/controller/LectureController.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureService.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureServiceImpl.java
<br/>
- ✨기능 추가/수정: 강의 정렬기능 수정
<br/>
=> ✨기능 추가/수정: 강의 정렬기능 수정

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/CustomIssueCouponRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java
- 제목 : feat(#92 ):  캠페인 발송 수정
<br/>
- 예약발송 시에만 배치 사용 -> 즉시 발송도 배치 사용하도록 변경했습니다.
<br/>
<br/>
<br/>
=> ♻️코드 수정: 캠페인 발송 수정

LearnsMate/src/main/java/intbyte4/learnsmate/payment/controller/PaymentController.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/repository/CustomPaymentRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/repository/CustomPaymentRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentService.java, LearnsMate/src/main/java/intbyte4/learnsmate/payment/service/PaymentServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepositoryCustom.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/repository/VOCRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCService.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCServiceImpl.java
<br/>
✨기능 추가: payment, voc 컬럼 정렬 적용
<br/>
=> ✨기능 추가: payment, voc 컬럼 정렬 적용

.github/workflows/deploy.yml, LearnsMate/src/main/java/intbyte4/learnsmate/admin/controller/TokenController.java, LearnsMate/src/main/java/intbyte4/learnsmate/common/config/RedisConfig.java, LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/lecture/repository/CustomLectureRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/JwtUtil.java, LearnsMate/src/main/java/intbyte4/learnsmate/security/WebSecurity.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/controller/VOCAiController.java, LearnsMate/src/main/java/intbyte4/learnsmate/voc/service/VOCAiService.java
<br/>
액세스 토큰 만료 시간 연장 기능을 수정했습니다. 확인한 뒤 오류가 나지 않게끔 해보겠습니다.
=> ♻️ 코드 수정: 액세스 토큰 만료 시간 연장 기능 수정

LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
수정하고서 프론트엔드에서 22년도 데이터를 포함하지 않았다는 것을 알아서 해당 부분 프론트엔드에서 수정했습니다.
int -> Integer로 수정한 것이지만 커밋하겠습니다.
=> ♻️ 코드 수정 : 일부 강의 구매 전환율 NULL로 받아오는 점 수정을 위해 커밋

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/batch/CampaignIssueCouponProcessor.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/batch/CampaignIssueCouponReader.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/batch/CampaignIssueCouponWriter.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/domain/vo/request/RequestRegisterCampaignVO.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/controller/CouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponFacade.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponService.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/service/CouponServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/controller/IssueCouponController.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/CustomIssueCouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/repository/CustomIssueCouponRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/issue_coupon/service/IssueCouponFacade.java
<br/>
✨기능 추가/수정: 쿠폰, 발급쿠폰 필터링x 정렬o 기능 추가
✨기능 추가/수정: 스프링 배치, 스케줄러 코드 수정
<br/>
=> ✨기능 추가/수정: 쿠폰, 발급쿠폰 필터링x 정렬o 기능 추가

LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/controller/CampaignTemplateController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepositoryCustom.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
<br/>
✨기능 추가/수정: 캠페인 템플릿 필터링, 컬럼정렬 기능 추가
=> ✨기능 추가/수정: 캠페인 템플릿 필터링, 컬럼정렬 기능 추가

LearnsMate/build.gradle
<br/>
✨기능 추가, 수정: build.gradle spotbugs 추가
=> ✨기능 추가, 수정: build.gradle spotbugs 추가

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/controller/CampaignController.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/repository/CampaignRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignService.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
- 제목 : feat(#): 캠페인 컬럼 정렬 추가
<br/>
- 캠페인 컬럼 정렬 기능 추가 
<br/>
<br/>
- 프론트엔드 css 수정
<br/>
=> ✨기능 추가: CampaignService -> findAllCampaignListBySort, findCampaignListByFilterAndSort 추가

LearnsMate/src/main/java/intbyte4/learnsmate/client/service/ClientService.java, LearnsMate/src/main/java/intbyte4/learnsmate/common/exception/StatusEnum.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/controller/MemberController.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberService.java
<br/>
✨기능 추가/수정: 회원 정렬 없는 필터링 기능 복원
=> ✨기능 추가/수정: 회원 정렬 없는 필터링 기능 복원

LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java, LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CouponRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/repository/MemberRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/member/service/MemberFacade.java
<br/>
삭제가 되지 않은 쿠폰만 조회를 위해 수정했습니다.
=> ♻️ 코드 수정 : 삭제가 되지 않은 쿠폰만 조회

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/mapper/CampaignMapper.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepository.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/repository/CampaignTemplateRepositoryImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/campaign_template/service/CampaignTemplateServiceImpl.java
- 제목 : feat(#344 ): 캠페인 템플릿 엑셀 다운로드 수정
<br/>
- 캠페인 템플릿 엑셀 다운로드 시 flag가 false인 데이터는 다운로드 되지 않도록 처리했습니다.
<br/>
<br/>
<br/>
=> ♻️코드 수정: 캠페인 템플릿 엑셀 다운로드 수정

LearnsMate/src/main/java/intbyte4/learnsmate/coupon/repository/CustomCouponRepositoryImpl.java
- 제목 : feat(#165 ):  CouponRepository 수정
<br/>
- flag가 false인 데이터는 조회되지 않도록 수정했습니다.
<br/>
<br/>
<br/>
=> ♻️코드 수정: CouponRepository 수정

LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
- 제목 : feat(issue 번호): 기능명
ex) feat(17): pull request template 작성
(확인 후 지워주세요)
<br/>
<br/>
<br/>
<br/>
=> ♻️ 코드 수정 : 강의 endYear, endMonth 일부 필터링 오류 확인을 위해 로그 추가

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java
- 제목 : feat(issue 번호): CampaignServiceImpl 수정
<br/>
- 캠페인 예약 발송 시간대 수정
<br/>
<br/>
<br/>
=> ♻️코드 수정: CampaignServiceImpl 수정

LearnsMate/src/main/java/intbyte4/learnsmate/lecture/service/LectureFacade.java
<br/>
일부 결제 데이터가 null으로 인한 오류를 수정했습니다.
=> ♻️ 코드 수정 : 강의 endYear, endMonth 일부 필터링 오류 수정

LearnsMate/src/main/java/intbyte4/learnsmate/campaign/service/CampaignServiceImpl.java, LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java
<br/>
♻️ 코드 수정 : 문자가 안 보내지는 오류 수정을 위해 커밋했습니다.
=> ♻️ 코드 수정 : 문자가 안 보내지는 오류 수정을 위해 커밋

LearnsMate/src/main/java/intbyte4/learnsmate/common/config/SchedulerConfig.java
=> ♻️ 코드 수정 : 확인을 위해 분마다 요청으로 수정
